### PR TITLE
rest API: add possibility to set coding in the URL

### LINKED ISSUE #213: Unable to send Unicode messages via REST API
Hello. Good day.
Using the code from the devel branch, I'm able to activate and use the REST API successfully.
The issue I'm facing is related to sending Unicode messages via the the REST API. Although the API accepts the messages correctly, they are delivered to the destination with most of the special characters stripped out.
If I sent the same message via the Web interface, ticking the Unicode checkbox, the message is delivered correctly.
Comparing the DB records from a message sent via Web Interface versus a message sent via REST API, I find that the "Coding" field on the "sentitems" table is different. 
Messages generated from the Web interface have the "Coding" as "Unicode_No_Compression" (assuming Unicode checkbox is ticket on the interface).
Messages generated via REST API have the "Coding" as "Default_No_Compression".
This is suggesting me that some is flag via the Web interface and not flagged via REST API.
Is there any way to flag messages from REST API to be marked and processed as Unicode?
Thank you.

### PR DESCRIPTION
**Pull request by tenzap**
If parameter is not set in the URL or is not "unicode" it will set "default"
Otherwise it will set the value for "coding" to unicode
To set coding to unicode, URL should contain
...&coding=unicode

**Fixes #213**

### CODE REVIEW

**Comment by kingster** [comment]
Imo this should be derived information by checking the charset and not passed in url (to avoid excess charges when not required)

**Comment by tenzap** [comment]
Is this really possible to detect charset ? Why isn't this already done so in other parts of Kalkun (eg on the new message panel, it has to be checked manually too)

**Comment by kingster** [comment]
It should be [technically possible](https://stackoverflow.com/questions/27599/reliable-sms-unicode-gsm-encoding-in-php). Other parts were never done because this happened to be a really old project and we dev's were not aware of this fancy methods at that point in time.

**Comment by tenzap** [comment]
To be consistent with the current way Kalkun works, I would accept this PR as is, and suggest to create a feature request for auto-set of unicode/default encoding wherever it is needed in kalkun

**Comment by kingster** [comment]
Agreed. Will create a issue for this.

**Comment by Sergio-** [comment]
My two cents:
Maybe use PHP's 
`mb_check_encoding($str, 'ASCII');`
In case it returns FALSE we should set coding=unicode.

**Pull request merged**
