### PR TITLE
CI Pipeline for Kalkun

### PR DESCRIPTION
**Pull request by kingster**

### CODE REVIEW

**Comment by kingster** [comment]
@tenzap How does this look to you? This removes `system` folder and is automatically installed using composer. Also, test-cases has its own dedicated folder

**Comment by kingster** [comment]
Composer (https://getcomposer.org/) is a library / dependency manager for php like npm/maven. 

Distribution packages will have everything in it (so offline installation is still possible) but those things won't be checked in git repo, those would get downloaded during build stage.

**Comment by tenzap** [comment]
What do you mean by build stage ?

During build stage there shouldn't be need for an internet connection (AFAIK at least on debian builders there is no access to the internet and the possibility to download anything)
Moreover, does that mean that a same version of kalkun, may have different versions of the things/packages it depends on ? IMO that would make kalkun "builds" of a same version unreproducible.

**Comment by kingster** [comment]
> What do you mean by build stage ?

When the package is being created. Package can be either zip or any other format.

> During build stage there shouldn't be need for an internet connection (AFAIK at least on debian builders there is no access to the internet and the possibility to download anything)

Most build platform would have internet/local mirror, as this is the standard process for downloading libraries. This is same construct for all languages. Php has evolved a lot over the past few years and no more requires to checkin dependencies into the code repo.

> Moreover, does that mean that a same version of kalkun, may have different versions of the things/packages it depends on ? IMO that would make kalkun "builds" of a same version unreproducible.

No. Decencies are exactly same, and managed by their commit-id or version number using the lock file.  Read more at https://stackoverflow.com/questions/10674641/composer-lock-how-does-it-work . As the lock file has exact commits/versions the exact version would be same across everyone. 

Apart from that, the artifact ( complete zip file which can be extracted and run) that is generated, can be simply downloaded  from the github ui (eg: https://github.com/back2arie/Kalkun/runs/632411915 )

**Comment by tenzap** [comment]
wow... 33.7MB instead of ~5MB...

**Comment by tenzap** [comment]
do you have any expectations regarding stop_manager plugin & this PR ?

**Comment by kingster** [comment]
> wow... 33.7MB now (compressed) instead of ~5MB before (uncompressed)...

That is because right now entire folder is being packed instead of the necessary ones, Unnecessary ones needs to be removed. 

> do you have any expectations regarding stop_manager plugin & this PR ?

Already responded on that PR. Lets not mix context between separate PR's

**Comment by kingster** [comment]
> wow... 33.7MB now (compressed) instead of ~5MB before (uncompressed)...

This is now no more. Current artifact size is 3.8 MB (compressed) Also this is slightly more than before, as it contains the codeigniter help docs which was previously not present. This seems good enough to me, as this cleans up the repo from a lot of non necessary files.

**Comment by tenzap** [comment]
AFAIK, random_compat is not needed with php7

**Pull request merged**
