### PR TITLE
Replace get_class() call, deprecated since PHP 8.3

### PR DESCRIPTION
**Pull request by alexandergotts**

### CODE REVIEW

**Review by tenzap — APPROVED** [review]

**Comment by tenzap** [comment]
When merging we would be careful to set the commit message. Something like. `Replace get_class() call, deprecated since PHP 8.3`

**Comment by alexandergotts** [comment]
fix

**Comment by tenzap** [comment]
You actually changed the title of the pr, not of the commit. Anyway, my message was intended to the person who will merge the pr.

**Review by kingster — APPROVED** [review]

**Comment by tenzap** [comment]
@alexandergotts, next time, please file the PR against "devel" branch, not master. I wasn't careful enough this time.

**Pull request merged**
