### PR TITLE
i18n: delete unused labels

### PR DESCRIPTION
**Pull request by tenzap**
Created with this script
```
for label in $(for line in $(awk -F \' '{print $2}' application/language/english/kalkun_lang.php | sort); do 
    COUNT=$(grep -lr "$line" application/ | wc -l); 
    echo $line $COUNT | grep 17 | awk '{print $1}'; 
done); do 
    for lang in application/language/*/kalkun_lang.php; do
        sed -i "/'$label'/d" $lang
    done
done
```

### CODE REVIEW

**Comment by kingster** [comment]
I don't think this is right, not possible that `kalkun_title` is not being used :)

**Comment by tenzap** [comment]
Where is it used then ?

**Comment by tenzap** [comment]
This one is more robust (there is one more item deleted)
```
for label in $(for line in $(awk -F \' '{print $2}' application/language/english/kalkun_lang.php | sort); do 
    COUNT=$(grep -lr "$line" application/ | wc -l)
    COUNT_WITHOUT_LANGFILE=$(grep -lr "$line" application/ | grep -vc application/language)
    echo $COUNT_WITHOUT_LANGFILE $line | grep ^0 | awk '{print $2}'; 
done); do 
    for lang in application/language/*/kalkun_lang.php; do
        sed -i "/'$label'/d" $lang
    done
done
```
Please prove it for `kalkun_title`. I would be surprised ;)

**Comment by kingster** [comment]
Woah! Couldn't find it! 

Though instead of deleting massively I would suggest fixing them instead.

**Comment by tenzap** [comment]
Any plan to merge this in a near future? If  yes, I will refresh the PR to fix the conflict, otherwise close the PR.

**Comment by kingster** [comment]
Hi @tenzap

Sorry for the delay. 

I am figuring out the future of this repo, just sorting few things out.

**Pull request merged**
