### PR TITLE
Better password handling

### PR DESCRIPTION
**Pull request by kingster**
Better password handling based on https://github.com/McBane87/docker-gammu-kalkun/tree/master/patches/04-kalkun-pwd-hash.patch

Note: for upgrade scenario(s) one would need to use password reset flow to reset password.

### CODE REVIEW

**Comment by tenzap** [comment]
I can't login anymore with latest devel...

**Comment by tenzap** [comment]
In case it helps someone:

```
* If you upgrade from 0.7.1 to 0.8
----------------------------------
- You will have to update the passwords for the kalkun users in the database.

- Default kalkun password has to be updated too
If column password of table "users" is
f0af18413d1c9e0366d8d1273160f55d5efeddfe
you have to set it to
$2y$10$Sg0IxngRIIp1qNITM8kWa.aJ26w58F97ByTzDKoRF/dyzKcLfx226

The SQL query for that is:
    UPDATE user SET password = '$2y$10$Sg0IxngRIIp1qNITM8kWa.aJ26w58F97ByTzDKoRF/dyzKcLfx226'
    WHERE password = 'f0af18413d1c9e0366d8d1273160f55d5efeddfe';

- To compute a hash for a given password run:
    $ php -r 'echo password_hash("new_password", PASSWORD_BCRYPT) . "\n";'
```

**Comment by kingster** [comment]
Alternatively just use the forgot password flow. It would automatically
handle everything.

**Comment by tenzap** [comment]
If I haven't set the phone number in the settings, it will send it to the default number... Not so cool...

**Pull request merged**
